//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CarRentalOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.RentalOrders = new HashSet<RentalOrder>();
        }
    
        public int Id { get; set; }
        public int TagNumber { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string CarYear { get; set; }
        public string Category { get; set; }
        public bool mp3Player { get; set; }
        public bool DVDPlayer { get; set; }
        public bool AirConditioner { get; set; }
        public bool Navigation { get; set; }
        public bool Available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalOrder> RentalOrders { get; set; }
    }
}
